### ISSUE TITLE
How to build a XML struct with a deeper level?

### ISSUE THREAD

**Issue by carpajr** [KDAB/KDSoap#174]
Hello,

I'm trying to build an XML message based on the structure followed exemplified, and I don't know how to add some params. I read the docs and see the function signature, but I didn't understand how I can do to build the message. 

Could someone help me?

**Example**:

```
<param>
    <user>abc</user>
    <available_item>
       <item>umbrela</item>
    <available_item>
    <available_item>
        <item>hat</item>
    </available_item>
</param>
```

**In the code**:

```
KDSoapMessage m;
KDSoapValueList p;
p.addArgument("user","abc");

// p.addArgument("available_item", ??>  <--- How could I do that?*

m.addArgument("param", p);
```
* I realize this method changed and now doesn't accept a KDSoapValueList as argument. 

How can I do to add "item" as a child of "available_item"?

**Comment by carpajr** [comment]
Hello!

~~KDSoapList.addArgument("name", KDSoapList p>~~  
Is not possible to add a KDSoapList using this method since 1.3 version (I think) of this lib. 


I found a way to solve my question, and I will explain how.

```
KDSoapList a, b;
a.addArgument("user",  "abc");
b.addArgument("item",  "umbrella");
KDSoapValue v("available_item", b)
a.append(v)
b.clear()
b.addArgument("item",  "hat");
KDSoapValue v("available_item", b)
a.append(v)
```

It is a kind verbose, but it works.

**Comment by dfaure-kdab** [comment]
Please note that this is not the usual way to use KDSoap.
Most people generate the above code using kdwsdl2cpp on a WSDL file.
This gives you a set of C++ classes on which you can call methods that take QLists etc.

**Comment by carpajr** [comment]
Dfaure,

Does this explain why the KDSoapList.addArgument signature has changed?

I'm facing some problems in integration between two systems and the partner having change XML schema very frequently. I considered that it would be less painful to generate a payload using the approach mentioned above, but I will rethink that. 

Thank you.

**Comment by dfaure-kdab** [comment]
I'm not sure which signature change you're referring to. The only source incompatible change I'm aware of is serialize/deserialize and KDQName, as documented in doc/CHANGES_1_8.txt

If your partner provides a WSDL file, then I strongly suggest generating code using that, so that you can actually detect schema changes (thanks to compilation errors), rather than having to debug runtime problems...

**Comment by carpajr** [comment]
> I'm not sure which signature change you're referring to.

David, I think until 1.3 version KDSoapList could be used as an argument:
https://docs.kdab.com/kdsoap/1.0.0/class_k_d_soap_value_list.html#acf2e157835a7ba96970204f53d0ff727

> If your partner provides a WSDL file, then I strongly suggest generating code using that, so that you can actually detect schema changes (thanks to compilation errors), rather than having to debug runtime problems...

I completely agree. I will make that.

**Comment by dfaure-kdab** [comment]
OK, you are referring to changes that happened in 2010...
(commit a64e3eb1eea1e7d7e20e55834acd7454a59dfd6e for the docu change and commit b2d337c409b2e643dec9a11623809eacf4c7d26b for the underlying change).

I don't consider this "a change" anymore, I consider this archeology, it was 9 years ago :-)

For sure the current API allows to nest XML another way (I'd have to refresh my memory for details), it's just not the best way to use KDSoap, the code generator does this for you. Since you're switching to that I'm closing the issue, for housekeeping purposes.
