### ISSUE TITLE
Fix include paths in the unit tests CMakeLists after the libkode uniformization

### ISSUE THREAD

**Issue by martonmiklos** [KDAB/KDSoap#216]
https://github.com/KDAB/KDSoap/blob/b1b7da075d2d5c38538905a282f3b5eb681694f2/unittests/CMakeLists.txt#L8

This line lists `../kdwsdl2cpp/common/ ../kdwsdl2cpp/schema/` which should be changed to `../kdwsdl2cpp/libkode/common/ ../kdwsdl2cpp/libkode/schema/`

BTW. ho do you used to build and execute unit tests? (I am working on Linux, either cmake or qmake approach is fine)

**Comment by dfaure-kdab** [comment]
Pass `-DKDSoap_TESTS=ON` to cmake in order to build them, `ctest` to run them.

My full script is:
`mkdir -p kdsoap/build_qt5_cmake && cd kdsoap/build_qt5_cmake && cmake ../KDSoap -DCMAKE_BUILD_TYPE=Debug -DKDSoap_TESTS=ON -DCMAKE_INSTALL_PREFIX=/d/kdab/inst/KDSoap-Qt5-cmake && make && make install`

Adjust the install prefix, obviously.

BTW, we're strongly considering dropping the qmake buildsystem in KDSoap, and only using cmake.
What do you think?

**Comment by martonmiklos** [comment]
Thanks for the test command, it is going to be useful.

> BTW, we're strongly considering dropping the qmake buildsystem in KDSoap, and only using cmake.
> What do you think?

Well I am ambivalent about qmake: I like and use it a lot, however I heard some rumours that it is going to be deprecated in the foreseeable future.

At the moment I am using the KDSOAP in a single -not-yet-finished- project with qmake, but I am not a paying customer ;). It is not a difficult thing and it would not be too hard to port to cmake. 

I see from the kode/kxml_compiler that maintaining dual build system could be a cumbersome task.
Do you have any timing plans about the dropping of the qmake build system? Does it have some other reason  than decreasing of the maintenance?

**Comment by dfaure-kdab** [comment]
Actually the rumours around qmake have been somewhat exaggerated. The fact is that Qt6 *itself* will be built with cmake rather than qmake. qmake will still be provided, during the lifetime of Qt6. But indeed it's like that Qt7 will be without qmake. It also means maintenance of qmake itself will be at a minimum.

Yes the main reason would be decreasing the maintenance -- not just for KDAB but also for contributors such as yourself, who constantly have to fight two buildsystems.... 
You're not a paying customer but you're a contributor so your opinion matters too.
There's no timeframe yet, we're still just thinking about it. But I thought I'd mention it before we all put much effort into adapting two buildsystems to the new source code layout and repo split. From KDAB's point of view, cmake would be sufficient.
We consider it the much more superior technical solution anyway, this isn't just because of probable future deprecation. In fact we're the ones who pushed and helped for Qt6 to adopt cmake :-)

**Comment by dfaure-kdab** [comment]
Meanwhile the qmake build system was removed. Is there any reason for this issue to remain open BTW? I'm still a bit unsure what it was about in the first place :). Please close if no longer applicable.

**Comment by martonmiklos** [comment]
The line what I linked:
https://github.com/KDAB/KDSoap/blob/b1b7da075d2d5c38538905a282f3b5eb681694f2/unittests/CMakeLists.txt#L8
still adds the following folders to the include path:
../kdwsdl2cpp/common/ ../kdwsdl2cpp/schema/

But after the libkode uniformization these folders does not exists anymore:

![kép](https://user-images.githubusercontent.com/1609182/120485797-bac60000-c3b4-11eb-8f91-5a5650266e2f.png)

If you agree it is a no time fix, I can submit a PR.

And yeah I messed up the title as I used to :smile:

**Comment by dfaure-kdab** [comment]
what's a "no time fix"? A fix that takes a trivial amount of time? Sounds like it yes.
Do you have `-Wmissing-include-dirs` enabled as a compiler flag? It helps detecting such issues.

**Comment by martonmiklos** [comment]
Dah, I missed it, in the current master it is fixed already:

https://github.com/KDAB/KDSoap/blob/master/unittests/CMakeLists.txt#L17
