### ISSUE TITLE
Call a service without using WSLD

### ISSUE THREAD

**Issue by MarcoITDev** [KDAB/KDSoap#281]
Hi,
I'm using KDSoap for an Android application.
Using only KDSoapClient.
I'm triyng to call this service:

http://www.dneonline.com/calculator.asmx?op=Add

But I can't pass the paramenter intA e intB:

const QString endPoint = QLatin1String("http://dneonline.com/calculator.asmx");
const QString messageNamespace = QLatin1String("http://tempuri.org/");
KDSoapClientInterface client(endPoint, messageNamespace);
KDSoapMessage message;            
message.addArgument(QLatin1String("intA"), 10);
message.addArgument(QLatin1String("intB"), 5);

KDSoapMessage response = client.call(QLatin1String("Add"), message);

I think passing paramenter with KDSoapMessage isn't correct. I don't want to use WSDL....

**Comment by dfaure-kdab** [comment]
Some facts:
- You don't have to use WSDL
- I don't believe KDSoap is incorrect
because these two things are rather well tested, see for instance testAddIntegers_sync() in unittests/webcalls/test_webcalls.cpp

The fact is that you might have to set things up for it to work, like:
- maybe you need  message.setQualified(true);
- maybe you need message.setUse(KDSoapMessage::LiteralUse);
- maybe you need to set client to RPCStyle
It all depends on how the service is configured. The WSDL file will tell you, even if you don't want to use it a compile time ;-)

**Comment by MarcoITDev** [comment]
> Some facts:
> 
> * You don't have to use WSDL
> * I don't believe KDSoap is incorrect
>   because these two things are rather well tested, see for instance testAddIntegers_sync() in unittests/webcalls/test_webcalls.cpp
> 
> The fact is that you might have to set things up for it to work, like:
> 
> * maybe you need  message.setQualified(true);
> * maybe you need message.setUse(KDSoapMessage::LiteralUse);
> * maybe you need to set client to RPCStyle
>   It all depends on how the service is configured. The WSDL file will tell you, even if you don't want to use it a compile time ;-)

You are right. I took 10 minutes to relax and I studied the WSDL and I found the solution.

Thank you for your job. KDSoap is a great library. And sorry for my post.
