### ISSUE TITLE
wsdl file message part return type mismatch on generated async subroutine

### ISSUE THREAD

**Issue by Chadster766** [KDAB/KDSoap#58]
Example:

```
<message name="SetDesiredLengthResponse">
      <part name="reply" type="xsd:boolean"/>
</message>
```
The generated prototypes are:

```
bool setDesiredLength( const QString& uom, int wholenum, int fractionalnum );
void asyncSetDesiredLength( const QString& uom, int wholenum, int fractionalnum );
```
The async prototype has the wrong return type of "void".

**Comment by tokoe-kdab** [comment]
Hej Chad,

the idea of the async interface is to _not_ return the result by return value (because therefor it would have to block the application until the HTTP response has been received), instead the result is delivered via the signal <methodName>Done() and <methodName>Error(). So in your case there should be a signal setDesiredLengthDone(bool reply) and a setDesiredLengthError(const KDSoapMessage &fault). The former is emitted whenever the SOAP call was successful, the latter in case of a protocol error.

**Comment by Chadster766** [comment]
Thanks for clearing that up :smile:
