### ISSUE TITLE
a .h file generation problem and soap client with the command kdwsdl2cpp

### ISSUE THREAD

**Issue by mohamedkeymanage** [KDAB/KDSoap#67]
I have a problem I try to generate a .h file from a wsdl file with the command here is the result kdwsdl2cpp : 

importing schema at file:///home/meditrans/KDSoap/KDSoap/xsd/CTX/ROOT_ctxlps_CTXLPS_V01_00.xsd
importing schema at file:///home/meditrans/KDSoap/KDSoap/xsd/CTX/ROOT_ctxbam_CTXBAM_V01_02.xsd
importing schema at http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
Downloading 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
Download successful
importing schema at http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
Downloading 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
Download successful
importing schema at http://www.w3.org/2001/xml.xsd
Downloading 'http://www.w3.org/2001/

Order finished without error but I do not find the .h file to generate the soap client.

**Comment by dfaure-kdab** [comment]
Can you show the command line for kdwsdl2cpp?

Is the wsdl file public?
Otherwise can you send it to me privately (with the necessary xsd files) so I can give it a try?

Maybe it crashes....

**Comment by mohamedkeymanage** [comment]
how I can send you the wsdl file in private ??
you have an email ??

**Comment by dfaure-kdab** [comment]
yes, david.faure at kdab.com

**Comment by mohamedkeymanage** [comment]
ok I sent thank you very much

**Comment by dfaure-kdab** [comment]
Fixed with 84f4e0208586192b4ac8dfbd18161d1b4426e8b4.

BTW you should have seen this the debug/warning output, before the fix:
Unable to open file [...]/DonneesVitale.xsd
Element not found: "http://www.sesam-vitale.fr/XMLschemas/Vitale" "donneesVitale" 
ERROR in type_teledeclarerMT: resolving element ref to 'vitale:donneesVitale': not found!

I wonder if you didn't paste the full log, or if these really didn't appear, which would be surprising.

**Comment by mohamedkeymanage** [comment]
thank you very much David
