### ISSUE TITLE
Client-side MTOM/XOP support

### ISSUE THREAD

**Issue by phbaer** [KDAB/KDSoap#77]
Hi there,

this is actually not really an issue but should be considered more like a question: I've implemented quick-any-dirty, prove-of-concept-ish support for MTOM/XOP attachments in on the client side (https://github.com/phbaer/KDSoap/commit/278cef42fc1e2338e80a9b9aff4079b0c56afb24). It only uses the start attachment and ignores all the other if there are any. It even does not properly check the MIME types yet, so ... it's really just a POC. It works pretty well for my use case which is a very simple one without binary attachments (and actually currently only a single attachment; unfortunately, the service always replies with MTOM/XOP compression enabled).

My question is now: would you/KDAB be interested in client-side MTOM/XOP support?

Thanks and cheers, phb

**Comment by dfaure** [comment]
Hello, sorry that I didn't reply earlier.

Yes, of course I'm interested in merging such a feature into KDSoap, there have been requests for it. 

You would just have to sign a CLA form so that this contribution can be used by KDAB under the commercial license, for commercial customers -- much like all Qt contributors agree to the Qt Company's CLA. I can make this happen on our side if you're interested.

**Comment by phbaer** [comment]
Also sorry for the late reply, was busy with other issues. We've worked around the MTOM/XOP issues and hence will not continue our efforts here. Sorry, but maybe someone else will eventually take care of that missing functionality.
