### ISSUE TITLE
Missing element even though it's in it

### ISSUE THREAD

**Issue by PeterBocan** [KDAB/KDSoap#86]
Hello guys, I am trying to generate client code for this WSDL

     kdwsdl2cpp -o Cribis.h -namespace Cribis 'https://ws.cribis.sk/v2.1/CribisSKWS.asmx?WSDL'

but I'm missing any generated code whatsoever, the error output 
  
     Error downloading 'https://ws.cribis.sk/v2.1/GR': Error transferring https://ws.cribis.sk/v2.1/GR - server replied: Not Found
    importing schema at http://microsoft.com/wsdl/types/
     Downloading 'http://microsoft.com/wsdl/types/'
     Download successful
     Error[2:2] unexpected character
     Element not found: "urn:crif-cribiscz-GetGlobalVerification:2014-08-19" "GetGlobalVerificationInput"
     ERROR in CribisGetGlobalVerification: resolving element ref to 's10:GetGlobalVerificationInput': not  found!

but I'm not sure what is going on here.

**Comment by dfaure** [comment]
Can you attach the WSDL file here so I can try it myself ?

Or if it's confidential, email it to david.faure at kdab (.com)

**Comment by dfaure** [comment]
In any case you might want to replace the import from https://ws.cribis.sk/v2.1/GR (which doesn't seem to exist) with the use of a local file.

**Comment by PeterBocan** [comment]
Here is the whole "package" that consists of WSDLs and XSDs.
[cribis.zip](https://github.com/KDAB/KDSoap/files/376387/cribisskws21definition.zip)

**Comment by dfaure** [comment]
There are some issues with this. You need to tell it where to import the namespaces from, like

 <s:import namespace="urn:crif-cribiscz-GetGlobalVerification:2014-08-19" schemaLocation="./GGV2.0.xsd" />

This solves the problem with GetGlobalVerificationOutput which is now available, but the error about s10:GetGlobalVerificationInput is still there because this element is not defined anywhere in the s10 namespace -- in particular it looks like it's missing from GGV2.0.xsd.

I will not be able to provide more free support of this kind, kdwsdl2cpp assumes valid WSDL as input, please make sure the WSDL file (and its associated XSD files) are valid and complete (e.g. using validation tools or other generation tools) before passing them to kdwsdl2cpp.

Let me know if you find an actual bug, but in this case, it really looks like invalid/incomplete schemas + missing schemaLocation attributes to be able to load these local xsd files.

(You can look at the other files in unittests/ to find many other wsdl files that include xsd file using schemaLocation="...")

**Comment by PeterBocan** [comment]
Can you tell me what ```Error[2:2] Unexpected character``` means?

**Comment by PeterBocan** [comment]
The ```GetGlobalVerificationInput``` is defined in WSDL file, which is weird (and I can not verify if it's a well defined structure) ... I'm not an expert in XML spec, thus I can't really say anything about  this voodoo I'm dealing with.

**Comment by dfaure** [comment]
Hi, did you manage to make it work?

**Comment by PeterBocan** [comment]
I did. Using GSoap, not KDSoap.

**Comment by dfaure** [comment]
Ah. Was any change necessary to the XSD/WSDL files (e.g. adding schemaLocation attributes)? 

I had missed the fact that GetGlobalVerificationInput didn't come from a XSD, but from the WSDL itself. There must be an issue with the import of the consecutive schema elements in that WSDL.

**Comment by PeterBocan** [comment]
I did not touch WSDL after all.

**Comment by dfaure-kdab** [comment]
Thanks for the information. I was able to find what the issue was. The .xsd files are unrelated and unused. As you pointed out, the types are all defined in the .wsdl file itself. However there are multiple schema tags inside the type tag, and it must be the first time kdsoap encounters this. Fixed in https://github.com/KDAB/KDSoap/commit/3e973d849d9b7f6c7217b00d94e9fd5ecb602aac. Thanks for the test wsdl file, and apologies for the delay, I know it's probably too late for you, unless you want the additional features from KDSoap (async jobs, qt integration etc.).
