### ISSUE TITLE
Generate only forward declaration

### ISSUE THREAD

**Issue by wodphoenix** [KDAB/KDSoap#87]
I try to use KDSoap and I am having problems using kdwsdl2cpp utility.
When generating a \* .h file it prescribes classified SOAPENC__Array class, but does not create its implementation.

Please tell me what I need to do that would be the realization of utility prescribed class?

[WSDL file link ](https://drive.google.com/open?id=0B_qbgdBb7o7RNk5kUV93RlMwVkU)
[*.h](https://drive.google.com/file/d/0B_qbgdBb7o7RdnQzNjJRX0pVUU0/view?pref=2&pli=1)
[*.cpp](https://drive.google.com/open?id=0B_qbgdBb7o7RM1BLNUlOTmxUNnc)

**Comment by dfaure** [comment]
This is a surprising WSDL file. Usually soapenc:Array is used as a base for a restriction which actually specifies the type of element in the array.

Example:
   <complexType name="ArrayOf_xsd_string">
    <complexContent>
     <restriction base="soapenc:Array">
      <attribute ref="soapenc:arrayType" wsdl:arrayType="xsd:string[]"/>
     </restriction>
    </complexContent>
   </complexType>

kdwsdl2cpp supports the above construct.

If you simply say <element name="attachments" nillable="true" type="soapenc:Array"/>
then attachments is an array of .... of what ? Not specified, so I don't see how to fix kdwsdl2cpp so that it generates a class that wraps an array, in proper C++. It would have to be pretty generic, using QVariant, which mostly defeats the point of generating a type-safe C++ API.
